### ISSUE TITLE
Wrong module 

### ISSUE THREAD

**Issue by Ranily57** [HiDeoo/starlight-blog#10]
### Describe the bug

Starlight Astro get his Page.astro in "Layout" and not "Layouts"

### To Reproduce

1. I tried to build
2. i get this error: [commonjs--resolver] Missing "./layouts/Page.astro" specifier in "@astrojs/starlight" package

### Expected behavior

I expect to the website to build

### How often does this bug happen?

Every time

### Additional Context

Here is the code i saw

#### starlight.d.ts
```js
declare module '@astrojs/starlight/layouts/Page.astro' {
  export default function Page(props: Record<string, unknown>): unknown
}
```

idk where else it is but when i change the path, i keep getting the error

**Comment by HiDeoo** [comment]
Good catch on that invalid path.

I have just published [a new version](https://github.com/HiDeoo/starlight-blog/releases/tag/v0.3.2) fixing it altho I don't think it should have an impact due to the hacky Vite shenanigans that this integration is doing (which may be why [the prod example](https://starlight-blog-example.vercel.app/blog) is building fine, my local repo is building fine too and I also tried setting up a new project and installing the extension and it worked too).

Could you give this new version and try and see if it fixes the issue for you for some reasons I don't understand yet 🤔

**Comment by Ranily57** [comment]
Still having the same error, here is the check i did: 

- Verify my node_module, the Page.astro is on @astrojs/starlight/layout/Page.astro ✅ 
- Try some change on the module directly ✅ 
- uninstall and reinstall all the node_modules ✅ 

![image](https://github.com/HiDeoo/starlight-blog/assets/62222362/2783525a-9b07-4b14-8871-56f9882fd8e3)

I saw this on my Visual Studio Code, it's the _Page.astro from your module, and it looks like he don't find the file, but as i said, i verified the path and it's good

I tried too with another file like astro.config.mjs
![image](https://github.com/HiDeoo/starlight-blog/assets/62222362/927e40ae-1744-4c6a-8080-c50a2d22af02)

It work, no error so i feel like it's from the module but for no reason he do not find it

**Comment by HiDeoo** [comment]
Is your project available publicly or would you be able to push a repro to GitHub so I can take a look?

**Comment by Ranily57** [comment]
Yes sure you can get on the [Repo](https://github.com/VRCFR/createurs) it's on the **dev** branch, the master one is for preview and the main one for production.

**Comment by HiDeoo** [comment]
Hmmm, this works for me. Could you try deleting the `.astro` directory you have locally and building again?

**Comment by Ranily57** [comment]
Still the same error 🤔 
![image](https://github.com/HiDeoo/starlight-blog/assets/62222362/f83738ac-5a76-401c-81ac-16cbccd0ae84)

**Comment by HiDeoo** [comment]
Weird that a fresh clone + `git switch dev` + `pnpm i` + `pnpm build` works for me 🤔 For sanity, could you try a fresh clone in a new directory even tho I don't think it would fix anything.

The only idea I have left is looking at your screenshot, you seem to be on Windows so maybe it could be OS related even tho I don't have any idea why right now and don't have any Windows machine at the moment to test it.

**Comment by Ranily57** [comment]
Still having the same error
![image](https://github.com/HiDeoo/starlight-blog/assets/62222362/712c83fe-f986-420f-9ff6-68bac89ebe16)

I don't really understand what is the trouble 🤔 Windows never did this before and it's only when i installed the blog module. I'll try it on linux and i'll tell you if i get the same trouble

**Comment by Ranily57** [comment]
Allright it's Windows, so it's not the module 👍 

![image](https://github.com/HiDeoo/starlight-blog/assets/62222362/0c6a4ea3-d1b2-4849-914d-5e86988d9ee0)

I'll check maybe how to solve this issue to keep working on windows on my repo. Thank's for your help, i'll continue working on the blog 😄

**Comment by HiDeoo** [comment]
> Allright it's Windows, so it's not the module 👍

Good to know, thanks for following up. If I get the time with a Windows machine at my disposal, I'll try to see what is causing the issue.

Something to note, the Vite "hacks" that this integration is using should go away when component customization lands in Starlight so that should automatically fix the issue.

Good luck on your blog posts and documentation. When you are done and if you want, to not hesitate to add your website to the [Starlight showcase](https://starlight.astro.build/showcase/).
